### PR TITLE
feat: support Xamarin, MAUI

### PR DESCRIPTION
**Pull request by anpin**
Hi @nogic1008 thanks for your effort with this repo!  I tried to use it in xamarin context and found that I need to do a few changes, maybe you would like to accept them in the main repo. 
- There was exception accessing file on configuration reload so I added `stream.Close()`
- Refactored `IWritableOptions` to inherit from `IOptionsMonitor` so we can access both `CurrentValue` and `OnChange` from an instance of `IWritableOptions`
- Added extension method for configuring `JsonWritableOptions` with a simple path in the form of `string` for cases where `IHostEnvironment` is not available

### CODE REVIEW

**Comment by anpin** [comment]
I kind of neglected that there were tests! Will add them later.

**Comment by nogic1008** [comment]
@anpin 
Could you please provide the Xamarin example?
I want to add it to `/sandbox` directory.

**Comment by anpin** [comment]
> @anpin Could you please provide the Xamarin example? I want to add it to `/sandbox` directory.

Should I rather add a sample for MAUI instead of Xamarin?

**Comment by anpin** [comment]
xamarin sample is also added. it relies on the added extension with explicit filepath as well as creates the file if it doesn't exist.

**Review by nogic1008 — APPROVED** [review]

**Comment by nogic1008** [comment]
@anpin 
Thank you for your contribution!!
I'll ship this changes on **Next Major** release because adding interface is breaking change.

ex.
- [Breaking Change Rules](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md)
- [A definitive guide to API-breaking changes in .NET](https://stackoverflow.com/questions/1456785/a-definitive-guide-to-api-breaking-changes-in-net)

**Comment by anpin** [comment]
@nogic1008 thanks for considering the changes and pointing me in the direction on how to improve my style of coding!

**Pull request merged**
